# Bu araç @keyiflerolsun tarafından | @KekikAkademi için yazılmıştır.

version: "3.9"

networks:
    local:
        driver: bridge

services:

    urunapi_py:
        container_name : urunapi_py
        image          : urunapi_py:latest
        restart        : always
        build          : ./UrunAPI_PY

        volumes:
            - ./UrunAPI_PY:/usr/src/UrunAPI_PY
        networks:
            - local
        ports:
            - 3310:5000


    website_php:
        container_name : website_php
        image          : php:apache
        restart        : always

        volumes:
            - ./WebSite_PHP:/var/www/html
        networks:
            - local
        ports:
            - 1453:80
        depends_on:
            - urunapi_py


    website_vue:
        container_name : website_vue
        image          : nginx:latest
        restart        : always

        volumes:
            - ./WebSite_Vue:/usr/share/nginx/html
        networks:
            - local
        ports:
            - 1071:80
        depends_on:
            - urunapi_py